jms_serializer:
    metadata:
        directories:
            Document:
                namespace_prefix: "App\\"
                path: "%kernel.project_dir%/config/serializer"
#            another-name:
#                namespace_prefix: "My\\BarBundle"
#                path: "@MyBarBundle/Resources/config/serializer"
