old_sound_rabbit_mq:
    connections:
        default:
            url: '%env(RABBITMQ_URL)%'
    consumers:
        send_email:
            connection:       default
            exchange_options: { name: 'messages', type: fanout }
            queue_options:    { name: 'messages'}
            callback:         App\Consumer\EmailNotificationConsumer
