_swagger_ui_gen:
  resource: '@SwaggerUIGenBundle/Resources/config/routing.yml'

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

api_login_check:
  path: /api/login_check

api_reset_password:
  path: /api/password
  controller: App\Controller\ApiController::reset

api_send_email:
  path: /api/email
  controller: App\Controller\ApiController::send