_swagger_ui_gen:
  resource: '@SwaggerUIGenBundle/Resources/config/routing.yml'

gesdinet_jwt_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh

api_login_check:
  path: /api/login_check

login:
  path: /login